### ISSUE TITLE
config DNS

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/scrypt-ts-by-example.github.io#1]
to redirect to by-example.scrypt.io.

Change the original by-example.scrypt.io to scrypt-by-example.scrypt.io

**Comment by zhfnjust** [comment]
i should be admin of this two repo, before configing it. @xhliu @msinkec

**Comment by zhfnjust** [comment]
Fixed
- https://by-example.scrypt.io
- https://scrypt-by-example.scrypt.io
