### ISSUE TITLE
Can the HTLC example run on BTC?

### ISSUE THREAD

**Issue by rdong8** [sCrypt-Inc/scrypt-ts-by-example.github.io#23]
Can the HTLC example be run on BTC, or does it still require Bitcoin SV?

**Comment by xhliu** [comment]
Yes, it should run on BTC with some slight change. Basically, make `timeLock()` compile to OP_CLTV/CSV directly, as in https://github.com/sCrypt-Inc/cat-contracts/blob/becdbd8d44cdca7405f32bd0b00f8285e923c82e/src/contracts/vaultCompleteWithdrawal.ts#L40.
